# Generated by Django 5.2.17 on 2026-08-30 08:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category', models.CharField(choices=[('development', 'Разработка'), ('design', 'Дизайн'), ('marketing', 'Маркетинг'), ('writing', 'Тексты'), ('other', 'Другое')], default='other', max_length=24, verbose_name='Категория')),
                ('budget_min', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимальный бюджет')),
                ('budget_max', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Максимальный бюджет')),
                ('skills', models.JSONField(blank=True, default=list, verbose_name='Навыки')),
                ('client_name', models.CharField(max_length=120, verbose_name='Имя заказчика')),
                ('client_company', models.CharField(blank=True, max_length=120, verbose_name='Компания')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('in_progress', 'В работе'), ('completed', 'Завершён')], default='active', max_length=24, verbose_name='Статус')),
                ('featured', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-featured', '-created_at'],
                'indexes': [models.Index(fields=['status', 'category'], name='marketplace_status_1ff29c_idx'), models.Index(fields=['-created_at'], name='marketplace_created_73869d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelancer_name', models.CharField(max_length=120, verbose_name='Имя исполнителя')),
                ('freelancer_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('cover_letter', models.TextField(verbose_name='Сопроводительное письмо')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость')),
                ('delivery_days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Срок в днях')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='marketplace.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='marketplace_project_9ae013_idx')],
            },
        ),
    ]
