# Generated by Django 5.2.17 on 2026-09-05 21:02

import django.core.validators
import django.db.models.deletion
import marketplace.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_passwordresetcode_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_days', models.PositiveIntegerField()),
                ('terms', models.TextField()),
                ('status', models.CharField(choices=[('signing', 'Ожидает подписей'), ('active', 'В работе'), ('review', 'На проверке'), ('completed', 'Завершён')], default='signing', max_length=16)),
                ('customer_signed_at', models.DateTimeField(blank=True, null=True)),
                ('freelancer_signed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=marketplace.models.private_work_path)),
                ('filename', models.CharField(max_length=255)),
                ('preview_text', models.TextField(max_length=15000)),
                ('preview_image', models.TextField(blank=True)),
                ('revision_note', models.TextField(blank=True, max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('provider', models.CharField(default='click', max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('prepared', 'Подготовлен'), ('paid', 'Оплачен'), ('cancelled', 'Отменён')], default='pending', max_length=16)),
                ('click_trans_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalletEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('kind', models.CharField(choices=[('topup', 'Пополнение'), ('income', 'Оплата работы'), ('purchase', 'Оплата заказа'), ('withdrawal', 'Вывод средств'), ('refund', 'Возврат')], max_length=24)),
                ('description', models.CharField(max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('destination', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('paid', 'Выполнен'), ('rejected', 'Отклонён')], default='pending', max_length=12)),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider_reference', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='passwordresetcode',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='has_passport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('uz', 'O‘zbekcha'), ('uz-cyrl', 'Ўзбекча'), ('en', 'English')], default='ru', max_length=8),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='rate_unit',
            field=models.CharField(choices=[('hour', 'За час'), ('day', 'За день')], default='hour', max_length=8),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('light', 'Светлая'), ('dark', 'Тёмная')], default='light', max_length=8),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposal',
            name='freelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает решения'), ('accepted', 'Принят'), ('rejected', 'Отклонён')], default='pending', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='nonnegative_wallet_balance'),
        ),
        migrations.AddConstraint(
            model_name='proposal',
            constraint=models.UniqueConstraint(fields=('project', 'freelancer'), name='unique_project_freelancer'),
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freelancer_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='marketplace.project'),
        ),
        migrations.AddField(
            model_name='contract',
            name='proposal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='marketplace.proposal'),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliverables', to='marketplace.contract'),
        ),
        migrations.AddField(
            model_name='payment',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='marketplace.contract'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='walletentry',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='marketplace.payment'),
        ),
        migrations.AddField(
            model_name='walletentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='walletentry',
            constraint=models.UniqueConstraint(fields=('payment', 'user', 'kind'), name='unique_payment_ledger_entry'),
        ),
    ]
