# Generated by Django 6.1 on 2026-09-05 22:07

import django.db.models.deletion
import marketplace.models
import uuid
from django.conf import settings
from django.db import migrations, models



def migrate_existing(apps, schema_editor):
    alias = schema_editor.connection.alias
    for item in apps.get_model('marketplace','WalletEntry').objects.using(alias).all().iterator():
        item.reference = uuid.uuid4()
        item.save(update_fields=['reference'], using=alias)
    Project = apps.get_model('marketplace','Project')
    Project.objects.using(alias).filter(status='active').update(status='published')
    for item in apps.get_model('marketplace','Profile').objects.using(alias).all().iterator():
        item.enabled_roles = [item.role] if item.role else []
        item.save(update_fields=['enabled_roles'], using=alias)
    for contract in apps.get_model('marketplace','Contract').objects.using(alias).select_related('project').all().iterator():
        contract.scope = contract.project.description
        if contract.status != 'completed':
            contract.status = ('awaiting_funding' if contract.customer_signed_at and contract.freelancer_signed_at else
                'customer_accepted' if contract.customer_signed_at else 'freelancer_accepted' if contract.freelancer_signed_at else 'draft')
            Project.objects.using(alias).filter(pk=contract.project_id).update(status='contracting')
        contract.save(update_fields=['scope','status'], using=alias)
    Category = apps.get_model('marketplace','Category')
    for slug,name in [('development','Разработка'),('design','Дизайн'),('marketing','Маркетинг'),('writing','Тексты'),('other','Другое')]:
        Category.objects.using(alias).get_or_create(slug=slug, defaults={'name':name})
    Skill = apps.get_model('marketplace','Skill')
    skills = {'React','JavaScript','TypeScript','Python','Django','Node.js','Next.js','Vue.js','HTML','CSS','Figma','UI/UX','PostgreSQL','SQL','Docker','Flutter','Swift','Kotlin','SEO','Copywriting','Branding','Go','PHP','Laravel','Git','REST API','Testing'}
    for model in ['Project','Profile']:
        for items in apps.get_model('marketplace',model).objects.using(alias).values_list('skills',flat=True):
            skills.update(s for s in items if isinstance(s,str) and len(s) <= 60)
    for name in sorted(skills):
        Skill.objects.using(alias).get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_unique_login_identifiers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('object_type', models.CharField(max_length=80)),
                ('object_id', models.CharField(max_length=80)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=24, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContractEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=5000)),
                ('status', models.CharField(choices=[('opened', 'Открыт'), ('evidence_collection', 'Сбор доказательств'), ('admin_review', 'На рассмотрении'), ('resolved', 'Решён')], default='opened', max_length=24)),
                ('resolution', models.TextField(blank=True)),
                ('freelancer_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=5000)),
                ('file', models.FileField(blank=True, upload_to=marketplace.models.private_work_path)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('system', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=40)),
                ('text', models.CharField(max_length=500)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=marketplace.models.attachment_path)),
                ('filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('text', models.TextField(max_length=3000)),
                ('communication', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quality', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('deadline', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('published', models.BooleanField(default=True)),
                ('moderation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='budget_type',
            field=models.CharField(default='fixed', max_length=8),
        ),
        migrations.AddField(
            model_name='contract',
            name='currency',
            field=models.CharField(default='UZS', max_length=3),
        ),
        migrations.AddField(
            model_name='contract',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='escrow_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contract',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contract',
            name='fee_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='contract',
            name='funded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contract',
            name='released_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contract',
            name='scope',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='enabled_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='professional_experience',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='profile',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='budget_type',
            field=models.CharField(choices=[('fixed', 'Fixed Price'), ('hourly', 'Hourly'), ('daily', 'Daily')], default='fixed', max_length=8),
        ),
        migrations.AddField(
            model_name='project',
            name='visibility',
            field=models.CharField(default='public', editable=False, max_length=8),
        ),
        migrations.AddField(
            model_name='walletentry',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='marketplace.contract'),
        ),
        migrations.AddField(
            model_name='walletentry',
            name='reference',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Ожидает подписей'), ('customer_accepted', 'Подтверждён заказчиком'), ('freelancer_accepted', 'Подтверждён исполнителем'), ('awaiting_funding', 'Ожидает резервирования'), ('active', 'В работе'), ('submitted', 'На проверке'), ('disputed', 'Спор'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='draft', max_length=24),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('contracting', 'Согласование договора'), ('in_progress', 'В работе'), ('review', 'На проверке'), ('completed', 'Завершён'), ('cancelled', 'Отменён'), ('disputed', 'Спор')], default='published', max_length=24, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает решения'), ('accepted', 'Принят'), ('rejected', 'Отклонён'), ('withdrawn', 'Отозван')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='walletentry',
            name='kind',
            field=models.CharField(choices=[('topup', 'Пополнение'), ('escrow_hold', 'Резервирование'), ('escrow_release', 'Выплата по договору'), ('platform_fee', 'Комиссия'), ('adjustment', 'Корректировка'), ('income', 'Оплата работы'), ('purchase', 'Оплата заказа'), ('withdrawal', 'Вывод средств'), ('refund', 'Возврат')], max_length=24),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('escrow_amount__gte', 0)), name='nonnegative_escrow'),
        ),
        migrations.AddConstraint(
            model_name='walletentry',
            constraint=models.UniqueConstraint(fields=('contract', 'user', 'kind'), name='unique_contract_ledger_entry'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractevent',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractevent',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='marketplace.contract'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dispute', to='marketplace.contract'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='opened_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispute',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='marketplace.contract'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='marketplace.contract'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectattachment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='marketplace.project'),
        ),
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='written_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='marketplace.contract'),
        ),
        migrations.AddField(
            model_name='review',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('contract', 'author'), name='one_review_per_author'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_range'),
        ),
        migrations.RunPython(migrate_existing, migrations.RunPython.noop),
        migrations.AlterField(model_name='walletentry', name='reference', field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
    ]
