# Generated by Django 6.1 on 2026-09-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_auditlog_category_contractevent_dispute_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payme_trans_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
