# Generated by Django 6.1 on 2026-09-07 19:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_relational_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickFiscalReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(default=dict)),
                ('click_payment_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('submitting', 'Проверяется результат отправки'), ('submitted', 'Ожидает чека CLICK'), ('ready', 'Чек получен'), ('review', 'Требует проверки')], default='pending', max_length=16)),
                ('qr_code_url', models.URLField(blank=True, max_length=2000)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=240)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='click_receipt', to='marketplace.payment')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='marketplace_status_659aa9_idx')],
            },
        ),
    ]
