# Generated by Django 6.1 on 2026-09-08 22:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_clickfiscalreceipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlatformFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('settlement_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('source', models.CharField(choices=[('settlement', 'Расчёт'), ('backfill', 'Историческая сверка')], default='settlement', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=180, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='marketplace_status_1ff29c_idx',
        ),
        migrations.AddField(
            model_name='category',
            name='icon_key',
            field=models.CharField(choices=[('code', 'code'), ('smartphone', 'smartphone'), ('bot', 'bot'), ('palette', 'palette'), ('megaphone', 'megaphone'), ('pen', 'pen'), ('shield', 'shield'), ('folder', 'folder')], default='folder', max_length=24),
        ),
        migrations.AddField(
            model_name='category',
            name='labels',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='contract',
            name='actual_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='fee_policy_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RenameField(
            model_name='project',
            old_name='category',
            new_name='legacy_category',
        ),
        migrations.AddField(
            model_name='project',
            name='skills_unspecified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='labels',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='skill',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_skills', to='marketplace.skill'),
        ),
        migrations.AddField(
            model_name='skill',
            name='normalized_name',
            field=models.CharField(editable=False, max_length=180, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='marketplace.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='categoryskill',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketplace.category'),
        ),
        migrations.AddField(
            model_name='categoryskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketplace.skill'),
        ),
        migrations.AddField(
            model_name='skill',
            name='categories',
            field=models.ManyToManyField(related_name='skills', through='marketplace.CategorySkill', to='marketplace.category'),
        ),
        migrations.AddField(
            model_name='platformfee',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='platform_fee', to='marketplace.contract'),
        ),
        migrations.AddField(
            model_name='skillalias',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='marketplace.skill'),
        ),
        migrations.AddConstraint(
            model_name='categoryskill',
            constraint=models.UniqueConstraint(fields=('category', 'skill'), name='unique_category_skill'),
        ),
        migrations.AddConstraint(
            model_name='platformfee',
            constraint=models.CheckConstraint(condition=models.Q(('fee_amount__gte', 0), ('fee_amount__lte', models.F('gross_amount')), ('fee_percent__gte', 0), ('fee_percent__lte', 100), ('gross_amount__gte', 0)), name='valid_platform_fee'),
        ),
    ]
