# Generated by Django 6.1 on 2026-09-12 21:29

import django.db.models.deletion
import marketplace.product_models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_original_design_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=8)),
                ('contact', models.CharField(max_length=254)),
                ('code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ContractAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_version', models.PositiveIntegerField()),
                ('changes', models.JSONField()),
                ('customer_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('freelancer_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LegalConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=120)),
                ('content_hash', models.CharField(max_length=64)),
                ('language', models.CharField(max_length=8)),
                ('content_snapshot', models.JSONField()),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-accepted_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='MultiFactorCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_secret', models.TextField()),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('setup_expires_at', models.DateTimeField()),
                ('last_counter', models.BigIntegerField(default=-1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayoutRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=40)),
                ('account', models.CharField(max_length=100)),
                ('provider_recipient_id', models.CharField(max_length=160)),
                ('destination', models.CharField(max_length=160)),
                ('verification_evidence', models.CharField(max_length=240)),
                ('verified_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ProposalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=5000)),
                ('file', models.FileField(blank=True, upload_to=marketplace.product_models.conversation_file_path)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProposalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityRateBucket',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalletOpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('evidence', models.CharField(max_length=240)),
                ('confirmed_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('action', models.CharField(max_length=32)),
                ('request_hash', models.CharField(max_length=64)),
                ('resulting_status', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='withdrawal',
            options={'ordering': ['-created_at'], 'permissions': [('operate_withdrawal', 'Can claim and settle withdrawals'), ('override_withdrawal', "Can reconcile another operator's withdrawal")]},
        ),
        migrations.AddField(
            model_name='contract',
            name='acceptance_criteria',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='contract',
            name='acceptance_workflow_version',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contract',
            name='accepted_deliverable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_by_contracts', to='marketplace.deliverable'),
        ),
        migrations.AddField(
            model_name='contract',
            name='demonstration_method',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='contract',
            name='review_days',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='contract',
            name='test_scenario',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='contract_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='deadline_snapshot',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='demo_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='review_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='review_escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='verification_steps',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='acceptance_criteria',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='project',
            name='clone_key',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='clone_request_hash',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='project',
            name='demonstration_method',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='project',
            name='review_days',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='project',
            name='source_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='copies', to='marketplace.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='test_scenario',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='walletentry',
            name='withdrawal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='marketplace.withdrawal'),
        ),
        migrations.AddField(
            model_name='walletentry',
            name='withdrawal_event',
            field=models.CharField(blank=True, choices=[('debit', 'Резерв вывода'), ('refund', 'Возврат вывода')], max_length=12),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='claim_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claimed_withdrawals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='payout_account',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='payout_provider',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='resolution_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='transfer_evidence',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оператора'), ('processing', 'Перевод обрабатывается'), ('reconciliation_required', 'Требуется сверка'), ('paid', 'Выполнен'), ('rejected', 'Отклонён'), ('cancelled', 'Отменён пользователем')], default='pending', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='walletentry',
            constraint=models.UniqueConstraint(condition=models.Q(('withdrawal__isnull', False)), fields=('withdrawal', 'withdrawal_event'), name='unique_withdrawal_event'),
        ),
        migrations.AddConstraint(
            model_name='walletentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('withdrawal__isnull', True), ('withdrawal_event', '')), models.Q(('amount__lt', 0), ('kind', 'withdrawal'), ('withdrawal__isnull', False), ('withdrawal_event', 'debit')), models.Q(('amount__gt', 0), ('kind', 'refund'), ('withdrawal__isnull', False), ('withdrawal_event', 'refund')), _connector='OR'), name='valid_withdrawal_event'),
        ),
        migrations.AddField(
            model_name='browsersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browser_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractamendment',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amendments', to='marketplace.contract'),
        ),
        migrations.AddField(
            model_name='contractamendment',
            name='proposed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='legalconsent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_consents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='multifactorcredential',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_credential', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payoutrecipient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_recipients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payoutrecipient',
            name='verified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verified_payout_recipients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='marketplace.payoutrecipient'),
        ),
        migrations.AddConstraint(
            model_name='withdrawal',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('provider_reference', ''), _negated=True), models.Q(('payout_provider', ''), _negated=True)), fields=('payout_provider', 'payout_account', 'provider_reference'), name='unique_external_withdrawal'),
        ),
        migrations.AddField(
            model_name='proposalconversation',
            name='proposal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='conversation', to='marketplace.proposal'),
        ),
        migrations.AddField(
            model_name='proposalmessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='marketplace.proposalconversation'),
        ),
        migrations.AddField(
            model_name='proposalmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposalreport',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='marketplace.proposalconversation'),
        ),
        migrations.AddField(
            model_name='proposalreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='walletopeningbalance',
            name='confirmed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_opening_balances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='walletopeningbalance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_opening_balance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawaloperation',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawaloperation',
            name='withdrawal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='marketplace.withdrawal'),
        ),
        migrations.AddConstraint(
            model_name='payoutrecipient',
            constraint=models.UniqueConstraint(fields=('user', 'provider', 'account', 'provider_recipient_id'), name='unique_payout_recipient'),
        ),
    ]
