# Generated by Django 6.1 on 2026-09-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_inventory_legacy_withdrawals'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verified_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified_phone',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
