# Generated by Django 6.1 on 2026-09-12 21:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_verified_contact_snapshots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScopedApiToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('secret_hash', models.CharField(max_length=64, unique=True)),
                ('scopes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='walletopeningbalance',
            name='source',
            field=models.CharField(choices=[('operator', 'Подтверждение оператора'), ('registration', 'Нулевой баланс при регистрации')], default='operator', max_length=16),
        ),
        migrations.AlterField(
            model_name='walletopeningbalance',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_opening_balances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='walletopeningbalance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confirmed_by__isnull', False), ('source', 'operator')), models.Q(('amount', 0), ('confirmed_by__isnull', True), ('source', 'registration')), _connector='OR'), name='valid_opening_balance_source'),
        ),
        migrations.AddField(
            model_name='scopedapitoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoped_api_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
