# Generated by Django 6.1 on 2026-09-13 18:48

import django.db.models.deletion
import django.utils.timezone
import marketplace.admin_control.models
import uuid
from django.conf import settings
from django.db import migrations, models


def queue_legacy_verifications(apps, schema_editor):
    Profile = apps.get_model('marketplace', 'Profile')
    Skill = apps.get_model('marketplace', 'Skill')
    Verification = apps.get_model('marketplace', 'SkillVerification')
    Report = apps.get_model('marketplace', 'ProposalReport')
    Audit = apps.get_model('marketplace', 'AuditLog')
    for profile in Profile.objects.exclude(verified_skills=[]).iterator():
        labels = profile.verified_skills if isinstance(profile.verified_skills, list) else []
        Audit.objects.create(action='legacy_verification_review', object_type='profile', object_id=str(profile.pk),
            reason='Исторические отметки сохранены для проверки; доверие не присвоено.',
            before={'verified_skills': profile.verified_skills}, after={'verified_skills': []},
            detail={'legacy_claims': profile.verified_skills})
        for label in labels:
            skill = Skill.objects.filter(name=label).first() if isinstance(label, str) else None
            if skill:
                Verification.objects.get_or_create(user_id=profile.user_id, skill_id=skill.pk,
                    defaults={'evidence_type': 'legacy', 'status': 'in_review',
                              'description': 'Историческая отметка без доказательств; требуется новая проверка.'})
        # Legacy claims are retained in queue; they never become approvals.
        profile.verified_skills = []
        profile.save(update_fields=['verified_skills'])
    Report.objects.filter(resolved_at__isnull=False).update(status='resolved')


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0018_scoped_tokens_and_opening_evidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(model_name='project', name='moderation_pending_public', field=models.BooleanField(default=True)),
        migrations.AddField(
            model_name='auditlog',
            name='after',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='before',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='operation_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='outcome',
            field=models.CharField(default='success', max_length=24),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_id',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='dispute',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dispute',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='public_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Ожидает проверки'), ('approved', 'Одобрено'), ('rejected', 'Нужны исправления'), ('hidden', 'Скрыто')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='project',
            name='moderation_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='proposalreport',
            name='decision',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposalreport',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_proposal_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposalreport',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('in_review', 'Рассматривается'), ('needs_information', 'Нужны сведения'), ('resolved', 'Решено'), ('rejected', 'Отклонено')], db_index=True, default='new', max_length=24),
        ),
        migrations.CreateModel(
            name='AccountRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('obligations', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lifted_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_restrictions', to=settings.AUTH_USER_MODEL)),
                ('lifted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lifted_restrictions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_restrictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminCommand',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=80)),
                ('request_hash', models.CharField(max_length=64)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=40)),
                ('object_id', models.PositiveBigIntegerField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Открыто'), ('resolved', 'Решено')], db_index=True, default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('restriction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='marketplace.accountrestriction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DisputeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispute_admin_notes', to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_notes', to='marketplace.dispute')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DisputePreview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('gross', models.DecimalField(decimal_places=2, max_digits=12)),
                ('snapshot', models.JSONField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_previews', to='marketplace.dispute')),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('open', 'Открыто'), ('in_review', 'Рассматривается'), ('waiting_user', 'Ожидает пользователя'), ('resolved', 'Решено')], db_index=True, default='open', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_tickets', to='marketplace.contract')),
                ('dispute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_tickets', to='marketplace.dispute')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administration', models.BooleanField(default=False)),
                ('text', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='marketplace.supportticket')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('profile', 'Профиль'), ('project', 'Заказ'), ('review', 'Отзыв'), ('message', 'Сообщение договора'), ('proposalmessage', 'Сообщение отклика')], max_length=32)),
                ('object_id', models.PositiveBigIntegerField()),
                ('reason', models.TextField(max_length=3000)),
                ('evidence', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_review', 'Рассматривается'), ('needs_information', 'Нужны сведения'), ('resolved', 'Решено'), ('rejected', 'Отклонено')], db_index=True, default='new', max_length=24)),
                ('decision', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='followups', to='marketplace.contentreport')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_content_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='marketplace_object__d11d98_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModerationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=40)),
                ('object_id', models.PositiveBigIntegerField()),
                ('action', models.CharField(max_length=40)),
                ('reason', models.TextField()),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='marketplace_object__a751f7_idx')],
            },
        ),
        migrations.CreateModel(
            name='SkillVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('portfolio', 'Портфолио'), ('certificate', 'Сертификат'), ('assessment', 'Проверка работы'), ('legacy', 'Историческая отметка')], max_length=40)),
                ('evidence_url', models.URLField(blank=True, max_length=2000)),
                ('evidence_file', models.FileField(blank=True, upload_to=marketplace.admin_control.models.verification_path)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('status', models.CharField(choices=[('submitted', 'Подано'), ('in_review', 'На проверке'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено'), ('revoked', 'Отозвано')], db_index=True, default='submitted', max_length=16)),
                ('decision', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_skills', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to='marketplace.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skill_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['submitted', 'in_review', 'approved'])), fields=('user', 'skill'), name='unique_active_skill_verification')],
            },
        ),
        migrations.RunPython(queue_legacy_verifications, migrations.RunPython.noop),
    ]
