# Generated by Django 6.1 on 2026-09-13 18:50

import django.db.models.deletion
import hashlib
import json
from decimal import Decimal
from pathlib import Path
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def import_published_content(apps, schema_editor):
    Content = apps.get_model('marketplace', 'ContentRevision')
    Setting = apps.get_model('marketplace', 'PlatformSettingRevision')
    # A checked-in immutable snapshot keeps replay deterministic after frontend edits.
    manifest = json.loads(Path(__file__).with_name('admin_content_seed.json').read_text(encoding='utf-8'))
    now = timezone.now()
    for language, texts in manifest['languages'].items():
        payload = {**texts, 'operator': manifest.get('operator', {}), 'support': manifest.get('support', {})}
        legal = {key: value for key, value in payload.items() if key not in {'homepage', 'faq'}}
        digest = hashlib.sha256(json.dumps(legal, ensure_ascii=False, sort_keys=True, separators=(',', ':')).encode()).hexdigest()
        Content.objects.get_or_create(language=language, version=1, defaults={
            'payload': payload, 'content_hash': digest, 'legal_version': manifest['version'],
            'approved': manifest.get('approved') is True, 'published_at': now, 'effective_at': now,
            'reason': 'Первоначальный импорт опубликованного контента Taskora; прежние согласия сохранены.'})
    values = {'platform_fee_percent': str(Decimal(str(settings.PLATFORM_FEE_PERCENT)).quantize(Decimal('0.01'))),
        'project_moderation_mode': 'post', 'support_response_hours': 48, 'dispute_response_hours': 48,
        'skill_verification_enabled': True, 'topups_paused': False, 'reserves_paused': False,
        'withdrawals_paused': False, 'maintenance_enabled': False, 'email_notifications_enabled': False,
        'sms_notifications_enabled': False}
    for key, value in values.items():
        Setting.objects.get_or_create(key=key, version=1, defaults={'value': value, 'published_at': now,
            'effective_at': now, 'reason': 'Первоначальная версия настроек; внешние платёжные настройки не изменены.'})


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_admin_panel_workflows'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('text', models.CharField(max_length=500)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('audience', models.JSONField(default=dict)),
                ('reason', models.TextField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('state', models.CharField(choices=[('draft', 'Черновик'), ('previewed', 'Предпросмотр'), ('queued', 'В очереди'), ('sent', 'Отправлено')], default='draft', max_length=16)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('recipient_hash', models.CharField(blank=True, max_length=64)),
                ('previewed_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='AdminJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('diagnostics', 'Диагностика'), ('reconcile', 'Сверка'), ('retry', 'Безопасная повторная обработка'), ('export', 'Экспорт CSV'), ('announcement', 'Доставка объявления')], max_length=24)),
                ('state', models.CharField(choices=[('queued', 'В очереди'), ('running', 'Выполняется'), ('succeeded', 'Завершено'), ('failed', 'Ошибка')], db_index=True, default='queued', max_length=16)),
                ('reason', models.TextField()),
                ('idempotency_key', models.UUIDField(unique=True)),
                ('request_hash', models.CharField(max_length=64)),
                ('dedupe_key', models.CharField(max_length=100)),
                ('parameters', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('storage_name', models.CharField(blank=True, editable=False, max_length=160)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('browser_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='marketplace.browsersession')),
            ],
            options={
                'verbose_name': 'фоновая задача',
                'verbose_name_plural': 'Фоновые задачи',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['kind', 'state', 'created_at'], name='marketplace_kind_bd4798_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state__in', ['queued', 'running'])), fields=('dedupe_key',), name='unique_active_admin_job')],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipients', to='marketplace.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('announcement', 'user'), name='unique_announcement_recipient')],
            },
        ),
        migrations.CreateModel(
            name='ContentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('base_version', models.PositiveIntegerField(default=0)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('publication_key', models.UUIDField(blank=True, null=True, unique=True)),
                ('publication_hash', models.CharField(blank=True, max_length=64)),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('uz', 'O‘zbekcha'), ('uz-cyrl', 'Ўзбекча'), ('en', 'English')], max_length=8)),
                ('payload', models.JSONField()),
                ('content_hash', models.CharField(max_length=64)),
                ('legal_version', models.CharField(max_length=120)),
                ('approved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'редакция контента',
                'verbose_name_plural': 'Редакции контента',
                'ordering': ['-created_at', '-pk'],
                'abstract': False,
                'indexes': [models.Index(fields=['language', 'published_at', 'effective_at'], name='marketplace_languag_0f6482_idx')],
                'constraints': [models.UniqueConstraint(fields=('language', 'version'), name='unique_content_revision')],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=160)),
                ('channel', models.CharField(default='internal', max_length=16)),
                ('template', models.CharField(max_length=80)),
                ('status', models.CharField(default='delivered', max_length=24)),
                ('detail', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='marketplace.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'доставка уведомления',
                'verbose_name_plural': 'Доставка уведомлений',
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('event_key', 'user', 'channel'), name='unique_notification_delivery')],
            },
        ),
        migrations.CreateModel(
            name='PlatformSettingRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('base_version', models.PositiveIntegerField(default=0)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('publication_key', models.UUIDField(blank=True, null=True, unique=True)),
                ('publication_hash', models.CharField(blank=True, max_length=64)),
                ('key', models.CharField(max_length=80)),
                ('value', models.JSONField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'редакция настройки',
                'verbose_name_plural': 'Редакции настроек',
                'ordering': ['-created_at', '-pk'],
                'abstract': False,
                'indexes': [models.Index(fields=['key', 'published_at', 'effective_at'], name='marketplace_key_9d88ce_idx')],
                'constraints': [models.UniqueConstraint(fields=('key', 'version'), name='unique_setting_revision')],
            },
        ),
        migrations.RunPython(import_published_content, migrations.RunPython.noop),
    ]
