"""Exercise the role template only in a disposable loopback QA database.

Requires the existing isolated test server started by run_isolated_postgres_tests.py.
The template's final COMMIT is replaced with assertions + ROLLBACK for every case.
No production URL or environment connection string is used or printed.
"""
import os
import subprocess
import uuid
from pathlib import Path

import psycopg
from psycopg import sql

ROOT = Path(__file__).resolve().parents[1]
QA = ROOT / ".taskora-qa" / "audit-postgresql"
PSQL = ROOT / ".taskora-qa" / "postgresql" / "pgsql" / "bin" / ("psql.exe" if os.name == "nt" else "psql")
password = (QA / "test-password").read_text(encoding="ascii")
tag = uuid.uuid4().hex[:10]
database = "taskora_role_qa_" + tag
migrator = "taskora_role_migration_" + tag
runtime = "taskora_role_runtime_" + tag
connection = {"host": "127.0.0.1", "port": 55442, "user": "taskora_audit", "password": password}
template = (ROOT / "ops" / "runtime-role.sql").read_text(encoding="utf-8")
assert template.count("\nCOMMIT;\n") == 1
environment = os.environ.copy()
environment["PGPASSWORD"] = password
flags = {"creationflags": subprocess.CREATE_NO_WINDOW} if os.name == "nt" else {}
checks = []


def exercise(name, *, target=None, schema="taskora_app", omitted=None, error=None):
    args = [str(PSQL), "-X", "-q", "-h", "127.0.0.1", "-p", "55442", "-U", "taskora_audit", "-d", database]
    parameters = {"target_database": target or database, "app_schema": schema, "migration_role": migrator, "runtime_role": runtime}
    for key, value in parameters.items():
        if key != omitted:
            args.extend(["-v", key + "=" + value])
    assertions = f"""
DO $$ BEGIN
  IF NOT has_table_privilege('{runtime}', 'taskora_app.marketplace_probe', 'SELECT,INSERT,UPDATE,DELETE')
     OR NOT has_sequence_privilege('{runtime}', 'taskora_app.marketplace_probe_id_seq', 'USAGE,SELECT')
     OR has_schema_privilege('{runtime}', 'taskora_app', 'CREATE') THEN
    RAISE EXCEPTION 'Runtime ACL assertion failed';
  END IF;
  IF EXISTS (SELECT FROM pg_roles WHERE rolname='{runtime}' AND
      (rolsuper OR rolcreatedb OR rolcreaterole OR rolreplication OR rolbypassrls OR rolinherit)) THEN
    RAISE EXCEPTION 'Runtime role attribute assertion failed';
  END IF;
END $$;
SET LOCAL ROLE {migrator};
CREATE TABLE taskora_app.marketplace_future (id serial PRIMARY KEY, value text);
RESET ROLE;
SET LOCAL ROLE {runtime};
INSERT INTO taskora_app.marketplace_probe(value) VALUES ('qa');
INSERT INTO taskora_app.marketplace_future(value) VALUES ('default-privilege-qa');
UPDATE taskora_app.marketplace_probe SET value='qa-updated';
DELETE FROM taskora_app.marketplace_probe;
DO $$ BEGIN
  CREATE TABLE taskora_app.unexpected_runtime_ddl(id integer);
  RAISE EXCEPTION 'Runtime unexpectedly has CREATE';
EXCEPTION WHEN insufficient_privilege THEN NULL;
END $$;
RESET ROLE;
ROLLBACK;
"""
    script = template.replace("\nCOMMIT;\n", "\n" + assertions)
    result = subprocess.run(args, input=script, text=True, capture_output=True, env=environment, **flags)
    if error:
        assert result.returncode != 0 and error in result.stderr, (name, result.returncode, result.stderr)
    else:
        assert result.returncode == 0, (name, result.stderr)
    with psycopg.connect(**connection, dbname=database, autocommit=True) as check:
        assert not check.execute("SELECT 1 FROM pg_roles WHERE rolname=%s", [runtime]).fetchone(), "Role escaped rollback"
    checks.append(name)


with psycopg.connect(**connection, dbname="postgres", autocommit=True) as admin:
    try:
        admin.execute(sql.SQL("CREATE ROLE {} NOLOGIN").format(sql.Identifier(migrator)))
        admin.execute(sql.SQL("CREATE DATABASE {}").format(sql.Identifier(database)))
        with psycopg.connect(**connection, dbname=database, autocommit=True) as fixture:
            fixture.execute(sql.SQL("CREATE SCHEMA taskora_app AUTHORIZATION {}").format(sql.Identifier(migrator)))
            fixture.execute("CREATE TABLE taskora_app.marketplace_probe(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, value text)")
            fixture.execute(sql.SQL("ALTER TABLE taskora_app.marketplace_probe OWNER TO {}").format(sql.Identifier(migrator)))
            exercise("valid scoped grants and future migration defaults roll back")
            exercise("wrong database rejected", target="not_the_connected_database", error="Wrong database")
            exercise("missing explicit schema rejected", omitted="app_schema", error="Supply app_schema")
            exercise("system schema rejected", schema="pg_catalog", error="System schemas")
            fixture.execute("GRANT CREATE ON SCHEMA taskora_app TO PUBLIC")
            exercise("inherited PUBLIC CREATE rejected", error="Inherited PUBLIC CREATE")
            fixture.execute("REVOKE CREATE ON SCHEMA taskora_app FROM PUBLIC")
            fixture.execute("CREATE TABLE taskora_app.other_application_secret(id integer)")
            fixture.execute(sql.SQL("ALTER TABLE taskora_app.other_application_secret OWNER TO {}").format(sql.Identifier(migrator)))
            exercise("unrelated object name rejected", error="Schema contains unrelated")
            fixture.execute("DROP TABLE taskora_app.other_application_secret")
            fixture.execute("CREATE TABLE taskora_app.marketplace_foreign_owner(id integer)")
            exercise("foreign object ownership rejected", error="Schema contains unrelated")
        print("Runtime role template:", len(checks), "checks PASS; every template transaction rolled back.")
        for check in checks:
            print("PASS:", check)
    finally:
        # Only names constructed above in this disposable test namespace are dropped.
        assert database.startswith("taskora_role_qa_") and migrator.startswith("taskora_role_migration_")
        admin.execute(sql.SQL("DROP DATABASE IF EXISTS {} WITH (FORCE)").format(sql.Identifier(database)))
        admin.execute(sql.SQL("DROP ROLE IF EXISTS {}").format(sql.Identifier(runtime)))
        admin.execute(sql.SQL("DROP ROLE IF EXISTS {}").format(sql.Identifier(migrator)))
