export const catalogCopy = {
  ru: {
    fee_revised: 'Комиссия исправлена',
    totalSpent: 'Потрачено',
    totalEarned: 'Заработано',
    escrowBalance: 'В резерве договора',
    viewReport: 'Посмотреть отчёт',
    activeProjects: 'Активные проекты',
    project: 'Проект',
    quickActions: 'Быстрые действия',
    topUp: 'Пополнить счёт',
    recommended: 'Рекомендуем',
    profileReadiness: 'Ваш профиль Taskora',
    completeProfileHint:
      'Добавьте опыт, навыки и работы, чтобы участникам было проще выбрать вас.',
    searchProjects: 'Поиск проектов…',
    spokenLanguages: 'Языки общения',
    languagesHint:
      'Каждый язык и уровень — с новой строки, например: English — B2.',
    eliteHeroBadge: 'IT-ПРОЕКТЫ · БЕЗОПАСНАЯ СДЕЛКА',
    eliteHeroText:
      'Проверяйте условия, общайтесь напрямую и оплачивайте результат через безопасную сделку.',
    explorePlatform: 'Посмотреть платформу',
    account: 'Аккаунт',
    projectStages: 'Этапы проекта',
    filters: 'Фильтры',
    itemTitle: 'Название',
    ordersSubtitle: 'Все ваши заказы в одном месте.',
    messagesSubtitle: 'Общайтесь с заказчиками и исполнителями.',
    recentMessages: 'Последние сообщения',
    chatAfterContract:
      'Переписка открывается после создания договора. Создайте заказ и согласуйте отклик исполнителя.',
    portfolio: 'Портфолио',
    noPortfolio: 'Работы пока не добавлены',
    addPortfolio: 'Добавить работу',
    services: 'Услуги',
    noServices: 'Услуги пока не добавлены',
    addService: 'Добавить услугу',
    achievements: 'Достижения',
    customerReviews: 'Отзывы заказчиков',
    noCustomerReviews: 'Отзывов пока нет',
    writeMessage: 'Написать сообщение',
    openProject: 'Открыть проект',
    onTimeProjects: 'Проекты в срок',
    professionalTitle: 'Специализация',
    location: 'Город и страна',
    projectLink: 'Ссылка на проект',
    coverImage: 'Обложка',
    removeItem: 'Удалить',
    servicePrice: 'Стоимость услуги',
    freelancerCommission: 'Комиссия с фрилансера',
    customerCommission: 'Комиссия с заказчика',
    removeSkill: 'Удалить навык',
    allSkills: 'Показать все навыки',
    recommendedSkills: 'Рекомендуемые навыки',
    selectedSkills: 'Выбрано',
    projectSkillHint: 'Рекомендуем 3–5 основных навыков, максимум 30.',
    profileSkillHint: 'Рекомендуем 5–15 основных навыков, максимум 30.',
    technologiesByFreelancer:
      'Не знаю технологии — пусть предложит исполнитель',
    technologiesDiscussed: 'Технологии обсуждаются с исполнителем',
    confirmClearSkills:
      'Удалить выбранные навыки и поручить выбор технологий исполнителю?',
    inactiveSkill: 'Недоступен для нового выбора',
    noSkillsFound: 'Ничего не найдено',
    feeEstimate: 'Предварительный расчёт',
    feeEstimateHint:
      'Ставка фиксируется при создании договора. Перед подтверждением проверьте его условия.',
    customerReserves: 'Заказчик резервирует',
    feePolicyChanged:
      'Ставка изменилась. Проверьте новый расчёт и подтвердите повторно.',
    actualSettlement: 'Фактический расчёт',
    originalPlan: 'Первоначальные условия',
    grossReleased: 'Начислено до комиссии',
    customerRefund: 'Возврат заказчику',
    feeNotSettled: 'Фактический расчёт пока не подтверждён.',
    skillMatch: 'Совпадение навыков',
    allSelectedSkills: 'Все выбранные',
    anySelectedSkill: 'Любой из выбранных',
    feeTerms:
      'Комиссию TASKORA оплачивает исполнитель: она удерживается из фактической выплаты при окончательной приёмке или решении спора. Заказчик резервирует согласованную сумму без надбавки TASKORA. Ставка фиксируется при создании договора и сохраняется при последующих изменениях тарифа. При полном возврате комиссия равна нулю; при частичном — рассчитывается только с суммы, присуждённой исполнителю. Пополнение, резервирование и вывод не создают повторного удержания комиссии TASKORA. Публикация и отклики бесплатны. Новый тариф объявляется отдельно и применяется только к новым договорам. Возможные сборы банков и платёжных провайдеров определяются их условиями.',
  },
  en: {
    fee_revised: 'Commission revised',
    totalSpent: 'Total spent',
    totalEarned: 'Total earned',
    escrowBalance: 'Reserved balance',
    viewReport: 'View report',
    activeProjects: 'Active projects',
    project: 'Project',
    quickActions: 'Quick actions',
    topUp: 'Add funds',
    recommended: 'Recommended',
    profileReadiness: 'Your Taskora profile',
    completeProfileHint:
      'Add your experience, skills and work so other members can choose you with confidence.',
    searchProjects: 'Search projects…',
    spokenLanguages: 'Languages',
    languagesHint:
      'One language and level per line, for example: English — B2.',
    eliteHeroBadge: 'IT PROJECTS · SECURE PAYMENTS',
    eliteHeroText:
      'Agree on the scope, communicate directly, and pay for the result with reserved funds.',
    explorePlatform: 'Explore the platform',
    account: 'Account',
    projectStages: 'Project stages',
    filters: 'Filters',
    itemTitle: 'Title',
    ordersSubtitle: 'Manage all your orders in one place.',
    messagesSubtitle: 'Stay in touch with clients and freelancers.',
    recentMessages: 'Recent messages',
    chatAfterContract:
      'Messaging opens after a contract is created. Create an order and agree on the freelancer’s proposal.',
    portfolio: 'Portfolio',
    noPortfolio: 'No work added yet',
    addPortfolio: 'Add work',
    services: 'Services',
    noServices: 'No services added yet',
    addService: 'Add a service',
    achievements: 'Achievements',
    customerReviews: 'Customer reviews',
    noCustomerReviews: 'No reviews yet',
    writeMessage: 'Send a message',
    openProject: 'Open project',
    onTimeProjects: 'Projects on time',
    professionalTitle: 'Specialization',
    location: 'City and country',
    projectLink: 'Project link',
    coverImage: 'Cover image',
    removeItem: 'Remove',
    servicePrice: 'Service price',
    freelancerCommission: 'Freelancer fee',
    customerCommission: 'Customer fee',
    removeSkill: 'Remove skill',
    allSkills: 'Show all skills',
    recommendedSkills: 'Recommended skills',
    selectedSkills: 'Selected',
    projectSkillHint: 'Choose 3–5 core skills; maximum 30.',
    profileSkillHint: 'Choose 5–15 core skills; maximum 30.',
    technologiesByFreelancer: 'Let the freelancer propose the technologies',
    technologiesDiscussed: 'Technologies to be agreed with the freelancer',
    confirmClearSkills:
      'Clear the selected skills and let the freelancer propose the technologies?',
    inactiveSkill: 'Unavailable for new selection',
    noSkillsFound: 'No matches found',
    feeEstimate: 'Estimated payout',
    feeEstimateHint:
      'The rate is fixed when the contract is created. Review its terms before confirming.',
    customerReserves: 'Customer reserves',
    feePolicyChanged:
      'The rate changed. Review the updated estimate and confirm again.',
    actualSettlement: 'Actual settlement',
    originalPlan: 'Original terms',
    grossReleased: 'Gross award',
    customerRefund: 'Customer refund',
    feeNotSettled: 'Actual settlement has not been confirmed yet.',
    skillMatch: 'Skill matching',
    allSelectedSkills: 'All selected',
    anySelectedSkill: 'Any selected',
    feeTerms:
      'The freelancer pays the TASKORA fee, deducted from the actual award at final acceptance or dispute resolution. The customer reserves the agreed amount without a TASKORA surcharge. The rate is fixed at contract creation and survives later rate changes. A full refund has zero commission; a partial refund charges commission only on the freelancer’s award. Top-ups, funding and withdrawals do not charge the TASKORA fee again. Posting and proposals are free. New rates are announced separately and apply only to new contracts. Banks and payment providers may charge fees under their own terms.',
  },
  uz: {
    fee_revised: 'Komissiya tuzatildi',
    totalSpent: 'Sarflangan mablag‘',
    totalEarned: 'Daromad',
    escrowBalance: 'Band qilingan mablag‘',
    viewReport: 'Hisobotlarni ko‘rish',
    activeProjects: 'Faol loyihalar ro‘yxati',
    project: 'Loyiha',
    quickActions: 'Tezkor amallar',
    topUp: 'Hisobni to‘ldirish',
    recommended: 'Tavsiya etiladi',
    profileReadiness: 'Taskora profilingiz',
    completeProfileHint:
      'Ishtirokchilar sizni tanlashi uchun tajriba, ko‘nikmalar va ishlaringizni qo‘shing.',
    searchProjects: 'Loyihalarni qidirish…',
    spokenLanguages: 'Tillar',
    languagesHint:
      'Har bir til va daraja yangi qatorda, masalan: English — B2.',
    eliteHeroBadge: 'IT LOYIHALAR · XAVFSIZ BITIM',
    eliteHeroText:
      'Shartlarni kelishing, bevosita muloqot qiling va natija uchun xavfsiz bitim orqali to‘lang.',
    explorePlatform: 'Tanishib ko‘rish',
    account: 'Hisob',
    projectStages: 'Loyiha bosqichlari',
    filters: 'Filtr',
    itemTitle: 'Nomi',
    ordersSubtitle: 'Barcha buyurtmalaringizni bir joydan boshqaring.',
    messagesSubtitle: 'Mijozlar va frilanserlar bilan muloqot tizimi.',
    recentMessages: 'Oxirgi xabarlar',
    chatAfterContract:
      'Yozishmalar shartnoma tuzilgach ochiladi. Buyurtma yarating va frilanser taklifini kelishing.',
    portfolio: 'Portfolio',
    noPortfolio: 'Ishlar hali qo‘shilmagan',
    addPortfolio: 'Ish qo‘shish',
    services: 'Xizmatlar',
    noServices: 'Xizmatlar hali qo‘shilmagan',
    addService: 'Xizmat qo‘shish',
    achievements: 'Yutuqlar',
    customerReviews: 'Mijozlar fikrlari',
    noCustomerReviews: 'Hali fikrlar yo‘q',
    writeMessage: 'Xabar yozish',
    openProject: 'Loyihani ochish',
    onTimeProjects: 'Muddatli loyihalar',
    professionalTitle: 'Mutaxassislik',
    location: 'Shahar va mamlakat',
    projectLink: 'Loyiha havolasi',
    coverImage: 'Muqova',
    removeItem: 'O‘chirish',
    servicePrice: 'Xizmat narxi',
    freelancerCommission: 'Frilanser komissiyasi',
    customerCommission: 'Buyurtmachi komissiyasi',
    removeSkill: 'Ko‘nikmani olib tashlash',
    allSkills: 'Barcha ko‘nikmalar',
    recommendedSkills: 'Tavsiya etilgan ko‘nikmalar',
    selectedSkills: 'Tanlangan',
    projectSkillHint: '3–5 asosiy ko‘nikma tavsiya etiladi, ko‘pi bilan 30 ta.',
    profileSkillHint:
      '5–15 asosiy ko‘nikma tavsiya etiladi, ko‘pi bilan 30 ta.',
    technologiesByFreelancer:
      'Texnologiyalarni bilmayman — ijrochi taklif qilsin',
    technologiesDiscussed: 'Texnologiyalar ijrochi bilan kelishiladi',
    confirmClearSkills:
      'Tanlangan ko‘nikmalar o‘chirilsin va texnologiyalarni ijrochi tanlasinmi?',
    inactiveSkill: 'Yangi tanlov uchun mavjud emas',
    noSkillsFound: 'Hech narsa topilmadi',
    feeEstimate: 'Taxminiy hisob-kitob',
    feeEstimateHint:
      'Stavka shartnoma yaratilganda belgilanadi. Tasdiqlashdan oldin shartlarni tekshiring.',
    customerReserves: 'Buyurtmachi zaxiraga qo‘yadi',
    feePolicyChanged:
      'Stavka o‘zgardi. Yangilangan hisobni tekshiring va qayta tasdiqlang.',
    actualSettlement: 'Amaldagi hisob-kitob',
    originalPlan: 'Dastlabki shartlar',
    grossReleased: 'Komissiyadan oldingi to‘lov',
    customerRefund: 'Buyurtmachiga qaytarish',
    feeNotSettled: 'Amaldagi hisob-kitob hali tasdiqlanmagan.',
    skillMatch: 'Ko‘nikmalar mosligi',
    allSelectedSkills: 'Barcha tanlanganlar',
    anySelectedSkill: 'Istalgan tanlangan',
    feeTerms:
      'TASKORA komissiyasini ijrochi to‘laydi: yakuniy qabul yoki nizo qarorida unga ajratilgan to‘lovdan ushlab qolinadi. Buyurtmachi kelishilgan summani TASKORA ustamasiz zaxiraga qo‘yadi. Stavka shartnoma yaratilganda belgilanadi va keyingi tarif o‘zgarishlarida saqlanadi. To‘liq qaytarishda komissiya nol; qisman qaytarishda faqat ijrochiga ajratilgan summadan hisoblanadi. Hisobni to‘ldirish, zaxiralash va pul yechishda TASKORA komissiyasi takroran olinmaydi. E’lon va takliflar bepul. Yangi tarif alohida e’lon qilinadi va faqat yangi shartnomalarga qo‘llanadi. Bank va to‘lov provayderlari yig‘imlari ularning shartlariga bog‘liq.',
  },
};
