export const mvpCopy = {
  ru: {
    payments: 'Платежи CLICK / PAYME',
    previewHint:
      'Материалы доступны для проверки. Исходный файл откроется после приёмки и выплаты исполнителю.',
    locked: 'Исходный файл доступен после приёмки работы',
    previewNotice:
      'Материалы доступны для проверки. Исходный файл откроется после приёмки и выплаты исполнителю.',
    dashboardPrompt: 'С чего начнём сегодня?',
    findFreelancers: 'Найти исполнителей',
    paymentMethod: 'Способ оплаты',
    payPayme: 'Оплатить через PAYME',
    notifications: 'Уведомления',
    messages: 'Сообщения',
    workChat: 'Рабочий чат',
    messageText: 'Напишите сообщение…',
    attachFile: 'Прикрепить файл',
    selectConversation: 'Выберите диалог',
    noNotifications: 'Новых уведомлений пока нет',
    readAll: 'Прочитать все',
    markRead: 'Прочитано',
    securePayment: 'Безопасная оплата',
    escrowHint:
      'Заказчик резервирует сумму до начала работы. Комиссия удерживается из выплаты исполнителю при приёмке. При споре средства остаются в резерве.',
    frozenBalance: 'В резерве',
    pendingBalance: 'Ожидаемая выплата',
    pendingWithdrawal: 'В процессе вывода',
    platformFee: 'Комиссия платформы',
    netAmount: 'Исполнителю',
    fundContract: 'Зарезервировать средства',
    acceptWork: 'Принять работу и выплатить',
    cancelContract: 'Отменить договор',
    confirm: 'Подтвердить',
    confirm_fund: 'Подтвердите списание доступных средств в резерв договора.',
    confirm_accept:
      'Подтвердите приёмку результата. Средства будут перечислены исполнителю.',
    confirm_cancel: 'Подтвердите отмену договора до начала работ.',
    confirm_dispute:
      'Подтвердите открытие спора. Выплата будет заблокирована до решения администратора.',
    dispute: 'Спор',
    openDispute: 'Открыть спор',
    disputeReason: 'Причина спора',
    disputeEvidence:
      'Оставьте комментарии и доказательства в рабочем чате. Администратор рассмотрит историю договора и распределит резерв.',
    reviews: 'Отзывы',
    rating: 'Рейтинг',
    reviewText: 'Ваш отзыв',
    leaveReview: 'Оставить отзыв',
    reviewSent: 'Отзыв опубликован',
    contractHistory: 'История договора',
    inReview: 'Работы на проверке',
    newProposals: 'Новые отклики',
    withdrawProposal: 'Отозвать отклик',
    acceptTerms: 'Я принимаю условия сервиса и политику обработки данных.',
    termsLink: 'Условия сервиса',
    privacyLink: 'Политика данных',
    passwordHint:
      'Минимум 8 символов: заглавная и строчная буквы, цифра и спецсимвол.',
    published: 'Опубликован',
    contracting: 'Согласование договора',
    customer_accepted: 'Подтверждён заказчиком',
    freelancer_accepted: 'Подтверждён исполнителем',
    awaiting_funding: 'Ожидает резервирования',
    submitted: 'На проверке',
    disputed: 'Открыт спор',
    withdrawn: 'Отозван',
    escrow_hold: 'Средства зарезервированы',
    escrow_release: 'Выплата по договору',
    platform_fee: 'Комиссия',
    adjustment: 'Корректировка',
    created: 'Договор создан',
    signed: 'Подтверждено',
    settled: 'Расчёты завершены',
    revision: 'Запрошена доработка',
    dispute_opened: 'Спор открыт',
    dispute_resolved: 'Спор решён',
    proposal: 'Новый отклик',
    proposal_rejected: 'Отклик отклонён',
    message: 'Новое сообщение',
    review: 'Отзыв',
    withdrawal_paid: 'Вывод завершён',
    withdrawal_rejected: 'Вывод отклонён',
    opened: 'Открыт',
    evidence_collection: 'Сбор доказательств',
    admin_review: 'Рассмотрение',
    resolved: 'Решён',
    budgetType: 'Тип бюджета',
    fixed: 'Фиксированная цена',
    hourly: 'Почасовая ставка',
    daily: 'Дневная ставка',
    saveDraft: 'Сохранить черновик',
    publish: 'Опубликовать',
    editProject: 'Редактировать заказ',
    cancelProject: 'Отменить заказ',
    confirmCancelProject: 'Отменить заказ? Запись сохранится в истории.',
    attachments: 'Вложения',
    chooseSkills: 'Выберите навыки',
    professionalExperience: 'Профессиональный опыт',
    available: 'Открыт к предложениям',
    changePassword: 'Сменить пароль',
    currentPassword: 'Текущий пароль',
    security: 'Безопасность',
    confirmWithdrawal: 'Подтверждаю сумму и реквизиты вывода',
    heroA: 'Найти фрилансера ещё никогда',
    heroB: 'не было',
    heroC: 'так просто',
    aboutPlatform: 'О платформе',
    trustText:
      'Надёжная платформа.\nДля фрилансеров и заказчиков.\nСоздана для рынка Узбекистана.',
    today: 'Начните сегодня',
    categories: 'Популярные категории',
    latestOrders: 'Новые заказы',
    specialists: 'Специалисты Taskora',
    explore: 'Смотреть все',
    footerPlatform: 'Платформа',
    documents: 'Документы',
    support: 'Поддержка',
    legalDraft: 'Условия MVP',
    termsBody:
      'Taskora связывает заказчика и исполнителя. Согласованные объём, цена и срок фиксируются в договоре. Работа начинается после резервирования средств. Заказчик принимает результат, запрашивает доработку или открывает спор. Приёмка освобождает резерв, при споре распределение определяет администратор. До начала работ договор можно отменить. История договоров и финансовых операций сохраняется. ONEID и сертифицированная электронная подпись пока не подключены.',
    privacyBody:
      'Профиль хранит имя, username, дату рождения, телефон, email и настройки. Публичный каталог показывает только данные профессионального профиля, без телефона, email и даты рождения. Договор, чат и файлы доступны участникам и уполномоченным администраторам. Пароли хранятся в виде хешей. Финансовая история и материалы споров сохраняются для аудита. Полные номера банковских карт не собираются.',
    legalNotice:
      'Юридические реквизиты оператора, контакты поддержки и окончательные сроки хранения должны быть заполнены владельцем платформы до коммерческого запуска.',
  },
  en: {
    payments: 'CLICK / PAYME payments',
    previewHint:
      'Review the preview materials. The source file becomes available after acceptance and release of funds.',
    locked: 'The source file is available after work acceptance',
    previewNotice:
      'Review materials are available. The source file unlocks after work acceptance and release of funds.',
    dashboardPrompt: 'What would you like to work on today?',
    findFreelancers: 'Find freelancers',
    paymentMethod: 'Payment method',
    payPayme: 'Pay with PAYME',
    notifications: 'Notifications',
    messages: 'Messages',
    workChat: 'Project chat',
    messageText: 'Write a message…',
    attachFile: 'Attach file',
    selectConversation: 'Select a conversation',
    noNotifications: 'No new notifications',
    readAll: 'Read all',
    markRead: 'Mark as read',
    securePayment: 'Secure payment',
    escrowHint:
      'The customer reserves funds before work starts. The platform fee is deducted from the freelancer payout on acceptance. Disputed funds remain frozen.',
    frozenBalance: 'Escrow balance',
    pendingBalance: 'Expected payout',
    pendingWithdrawal: 'Pending withdrawal',
    platformFee: 'Platform fee',
    netAmount: 'Freelancer receives',
    fundContract: 'Reserve funds',
    acceptWork: 'Accept work and release funds',
    cancelContract: 'Cancel contract',
    confirm: 'Confirm',
    confirm_fund: 'Confirm moving available funds into contract escrow.',
    confirm_accept:
      'Confirm acceptance. The funds will be released to the freelancer.',
    confirm_cancel: 'Confirm cancellation before work begins.',
    confirm_dispute:
      'Confirm opening a dispute. Payout will remain frozen until an administrator decides.',
    dispute: 'Dispute',
    openDispute: 'Open dispute',
    disputeReason: 'Reason for dispute',
    disputeEvidence:
      'Add comments and evidence to the project chat. An administrator will review the contract history and distribute the escrow.',
    reviews: 'Reviews',
    rating: 'Rating',
    reviewText: 'Your review',
    leaveReview: 'Leave review',
    reviewSent: 'Review published',
    contractHistory: 'Contract history',
    inReview: 'Work in review',
    newProposals: 'New proposals',
    withdrawProposal: 'Withdraw proposal',
    acceptTerms: 'I accept the service terms and data policy.',
    termsLink: 'Service terms',
    privacyLink: 'Data policy',
    passwordHint:
      'At least 8 characters: uppercase and lowercase letters, a number and a special character.',
    published: 'Published',
    contracting: 'Contract negotiation',
    customer_accepted: 'Customer confirmed',
    freelancer_accepted: 'Freelancer confirmed',
    awaiting_funding: 'Awaiting funding',
    submitted: 'Submitted',
    disputed: 'Disputed',
    withdrawn: 'Withdrawn',
    escrow_hold: 'Funds reserved',
    escrow_release: 'Contract payout',
    platform_fee: 'Platform fee',
    adjustment: 'Adjustment',
    created: 'Contract created',
    signed: 'Confirmed',
    settled: 'Settlement complete',
    revision: 'Revision requested',
    dispute_opened: 'Dispute opened',
    dispute_resolved: 'Dispute resolved',
    proposal: 'New proposal',
    proposal_rejected: 'Proposal rejected',
    message: 'New message',
    review: 'Review',
    withdrawal_paid: 'Withdrawal completed',
    withdrawal_rejected: 'Withdrawal rejected',
    opened: 'Opened',
    evidence_collection: 'Evidence collection',
    admin_review: 'Admin review',
    resolved: 'Resolved',
    budgetType: 'Budget type',
    fixed: 'Fixed price',
    hourly: 'Hourly',
    daily: 'Daily',
    saveDraft: 'Save draft',
    publish: 'Publish',
    editProject: 'Edit project',
    cancelProject: 'Cancel project',
    confirmCancelProject: 'Cancel this project? It will remain in history.',
    attachments: 'Attachments',
    chooseSkills: 'Select skills',
    professionalExperience: 'Professional experience',
    available: 'Available for work',
    changePassword: 'Change password',
    currentPassword: 'Current password',
    security: 'Security',
    confirmWithdrawal: 'I confirm the withdrawal amount and destination',
    heroA: 'Finding a freelancer has never',
    heroB: 'been',
    heroC: 'this easy',
    aboutPlatform: 'About the platform',
    trustText:
      'A platform built on trust.\nFor freelancers and customers.\nCreated for Uzbekistan.',
    today: 'Start today',
    categories: 'Popular categories',
    latestOrders: 'Latest projects',
    specialists: 'Taskora specialists',
    explore: 'View all',
    footerPlatform: 'Platform',
    documents: 'Documents',
    support: 'Support',
    legalDraft: 'MVP terms',
    termsBody:
      'Taskora connects customers and freelancers. Scope, price and delivery time are recorded in the contract. Work starts after funds are reserved. Customers accept results, request revisions or open disputes. Acceptance releases escrow; administrators resolve disputed funds. Contracts can be cancelled before funding. Contract and payment history is retained. ONEID and certified electronic signatures are not connected yet.',
    privacyBody:
      'Accounts store names, usernames, birth dates, phone numbers, email addresses and preferences. Public profiles exclude phone, email and birth date. Contracts, chat and private files are available to participants and authorised administrators. Passwords are hashed. Financial and dispute records are retained for audit. Full card numbers are not collected.',
    legalNotice:
      'The platform owner must provide operator details, support contacts and final retention periods before commercial launch.',
  },
  uz: {
    payments: 'CLICK / PAYME to‘lovlari',
    previewHint:
      'Natijani tekshiring. Asl fayl ish qabul qilinib, mablag‘ ijrochiga o‘tkazilgandan keyin ochiladi.',
    locked: 'Asl fayl ish qabul qilingandan keyin ochiladi',
    previewNotice:
      'Natijani tekshiring. Asl fayl ish qabul qilinib, mablag‘ ijrochiga o‘tkazilgandan keyin ochiladi.',
    dashboardPrompt: 'Bugun qanday ish boshlaymiz?',
    findFreelancers: 'Ijrochilarni topish',
    paymentMethod: 'To‘lov usuli',
    payPayme: 'PAYME orqali to‘lash',
    notifications: 'Bildirishnomalar',
    messages: 'Xabarlar',
    workChat: 'Ishchi chat',
    messageText: 'Xabar yozing…',
    attachFile: 'Fayl biriktirish',
    selectConversation: 'Suhbatni tanlang',
    noNotifications: 'Yangi bildirishnomalar yo‘q',
    readAll: 'Barchasini o‘qish',
    markRead: 'O‘qildi',
    securePayment: 'Xavfsiz to‘lov',
    escrowHint:
      'Buyurtmachi ish boshlanishidan oldin mablag‘ni band qiladi. Komissiya natija qabul qilinganda ijrochi to‘lovidan ushlanadi. Nizo paytida mablag‘ band holda qoladi.',
    frozenBalance: 'Band mablag‘',
    pendingBalance: 'Kutilayotgan to‘lov',
    pendingWithdrawal: 'Chiqarilayotgan mablag‘',
    platformFee: 'Platforma komissiyasi',
    netAmount: 'Ijrochiga',
    fundContract: 'Mablag‘ni band qilish',
    acceptWork: 'Ishni qabul qilish va to‘lash',
    cancelContract: 'Shartnomani bekor qilish',
    confirm: 'Tasdiqlash',
    confirm_fund: 'Mablag‘ni shartnoma uchun band qilishni tasdiqlang.',
    confirm_accept:
      'Natijani qabul qilishni tasdiqlang. Mablag‘ ijrochiga o‘tkaziladi.',
    confirm_cancel:
      'Ish boshlanishidan oldin shartnomani bekor qilishni tasdiqlang.',
    confirm_dispute:
      'Nizo ochilishini tasdiqlang. Administrator qarorigacha to‘lov bloklanadi.',
    dispute: 'Nizo',
    openDispute: 'Nizo ochish',
    disputeReason: 'Nizo sababi',
    disputeEvidence:
      'Izoh va dalillarni ishchi chatga yuboring. Administrator shartnoma tarixini ko‘rib chiqib, mablag‘ni taqsimlaydi.',
    reviews: 'Sharhlar',
    rating: 'Reyting',
    reviewText: 'Sharhingiz',
    leaveReview: 'Sharh qoldirish',
    reviewSent: 'Sharh e’lon qilindi',
    contractHistory: 'Shartnoma tarixi',
    inReview: 'Tekshiruvdagi ishlar',
    newProposals: 'Yangi takliflar',
    withdrawProposal: 'Taklifni qaytarish',
    acceptTerms: 'Xizmat shartlari va ma’lumotlar siyosatiga roziman.',
    termsLink: 'Xizmat shartlari',
    privacyLink: 'Ma’lumotlar siyosati',
    passwordHint:
      'Kamida 8 belgi: katta va kichik harf, raqam va maxsus belgi.',
    published: 'E’lon qilingan',
    contracting: 'Shartnomani kelishish',
    customer_accepted: 'Buyurtmachi tasdiqladi',
    freelancer_accepted: 'Ijrochi tasdiqladi',
    awaiting_funding: 'Mablag‘ kutilmoqda',
    submitted: 'Tekshiruvda',
    disputed: 'Nizo ochilgan',
    withdrawn: 'Qaytarilgan',
    escrow_hold: 'Mablag‘ band qilindi',
    escrow_release: 'Shartnoma bo‘yicha to‘lov',
    platform_fee: 'Komissiya',
    adjustment: 'Tuzatish',
    created: 'Shartnoma yaratildi',
    signed: 'Tasdiqlandi',
    settled: 'Hisob-kitob yakunlandi',
    revision: 'Tuzatish so‘raldi',
    dispute_opened: 'Nizo ochildi',
    dispute_resolved: 'Nizo hal qilindi',
    proposal: 'Yangi taklif',
    proposal_rejected: 'Taklif rad etildi',
    message: 'Yangi xabar',
    review: 'Sharh',
    withdrawal_paid: 'Mablag‘ chiqarildi',
    withdrawal_rejected: 'Chiqarish rad etildi',
    opened: 'Ochiq',
    evidence_collection: 'Dalillar yig‘ish',
    admin_review: 'Ko‘rib chiqilmoqda',
    resolved: 'Hal qilingan',
    budgetType: 'Byudjet turi',
    fixed: 'Belgilangan narx',
    hourly: 'Soatlik',
    daily: 'Kunlik',
    saveDraft: 'Qoralama saqlash',
    publish: 'E’lon qilish',
    editProject: 'Buyurtmani tahrirlash',
    cancelProject: 'Buyurtmani bekor qilish',
    confirmCancelProject: 'Buyurtma bekor qilinsinmi? U tarixda saqlanadi.',
    attachments: 'Ilovalar',
    chooseSkills: 'Ko‘nikmalarni tanlang',
    professionalExperience: 'Kasbiy tajriba',
    available: 'Takliflarga ochiq',
    changePassword: 'Parolni almashtirish',
    currentPassword: 'Joriy parol',
    security: 'Xavfsizlik',
    confirmWithdrawal: 'Chiqarish miqdori va rekvizitlarini tasdiqlayman',
    heroA: 'Frilanser topish hech qachon',
    heroB: 'bu qadar',
    heroC: 'oson bo‘lmagan',
    aboutPlatform: 'Platforma haqida',
    trustText:
      'Ishonchli platforma.\nFrilanserlar va mijozlar uchun.\nO‘zbekiston bozori uchun yaratilgan.',
    today: 'Bugun boshlang',
    categories: 'Mashhur kategoriyalar',
    latestOrders: 'Yangi buyurtmalar',
    specialists: 'Taskora mutaxassislari',
    explore: 'Barchasini ko‘rish',
    footerPlatform: 'Platforma',
    documents: 'Hujjatlar',
    support: 'Yordam',
    legalDraft: 'MVP shartlari',
    termsBody:
      'Taskora buyurtmachi va ijrochini bog‘laydi. Ish hajmi, narx va muddat shartnomada belgilanadi. Mablag‘ band qilingach ish boshlanadi. Buyurtmachi natijani qabul qiladi, tuzatish so‘raydi yoki nizo ochadi. Qabul qilish band mablag‘ni bo‘shatadi; nizoda administrator qaror qiladi. Mablag‘ band qilinishidan oldin shartnoma bekor qilinishi mumkin. Shartnoma va to‘lov tarixi saqlanadi. ONEID va sertifikatlangan elektron imzo hali ulanmagan.',
    privacyBody:
      'Profil ism, username, tug‘ilgan sana, telefon, email va sozlamalarni saqlaydi. Ochiq profilda telefon, email va tug‘ilgan sana ko‘rsatilmaydi. Shartnoma, chat va fayllar qatnashchilar hamda vakolatli administratorlarga ochiq. Parollar xesh shaklida saqlanadi. Moliyaviy tarix va nizo materiallari audit uchun saqlanadi. Bank kartasining to‘liq raqami yig‘ilmaydi.',
    legalNotice:
      'Tijorat ishga tushirilishidan oldin platforma egasi operator rekvizitlari, yordam kontaktlari va ma’lumot saqlash muddatlarini belgilashi kerak.',
  },
};
