'use client';

import Link from 'next/link';
import { Bell, BriefcaseBusiness, CheckCircle2, ChevronRight, Clock3, Home, LogOut, Mail, Menu, MessageSquare, Search, Settings, ShieldCheck, Star, UserRound, Wallet, X } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { useApp } from '@/components/app-providers';
import { fetchProjects, logout } from '@/lib/api';

const labels = {
  uz: { home: 'Bosh sahifa', profile: 'Profil', orders: 'Buyurtmalar', messages: 'Xabarlar', wallet: 'Hamyon', settings: 'Sozlamalar', welcome: 'Xush kelibsiz', subtitle: 'Bugun qanday ishlashni xohlaysiz?', find: 'Buyurtma topish', create: 'Buyurtma berish', active: 'Faol loyihalar', completed: 'Yakunlangan', proposals: 'Takliflar', earned: 'Jami daromad', recommended: 'Siz uchun tavsiya etilgan buyurtmalar', all: 'Barchasini ko‘rish', details: 'Batafsil', rating: 'Reyting', projects: 'Muvaffaqiyatli loyihalar', deadline: 'Muddatli loyihalar', activity: 'Platformadagi faoliyat', skills: 'Ko‘nikmalar', portfolio: 'Portfolio', write: 'Xabar yozish', order: 'Buyurtma berish', logout: 'Chiqish' },
  ru: { home: 'Главная', profile: 'Профиль', orders: 'Заказы', messages: 'Сообщения', wallet: 'Кошелёк', settings: 'Настройки', welcome: 'Добро пожаловать', subtitle: 'Как хотите поработать сегодня?', find: 'Найти заказ', create: 'Создать заказ', active: 'Активные проекты', completed: 'Завершено', proposals: 'Предложения', earned: 'Общий доход', recommended: 'Рекомендованные заказы', all: 'Смотреть все', details: 'Подробнее', rating: 'Рейтинг', projects: 'Успешных проектов', deadline: 'Выполнено в срок', activity: 'На платформе', skills: 'Навыки', portfolio: 'Портфолио', write: 'Написать', order: 'Предложить заказ', logout: 'Выйти' },
};

const fallbackProjects = [
  { id: 1, title: 'Landing Page dizayni', category: 'design', description: 'Fintech mahsuloti uchun zamonaviy va mobilga mos landing page.', budget_min: '1000000', budget_max: '3000000', skills: ['UI/UX', 'Figma'], proposal_count: 6 },
  { id: 2, title: 'Instagram uchun 10 ta post dizayni', category: 'design', description: 'Yangi brend uchun yagona uslubdagi ijtimoiy tarmoq postlari.', budget_min: '800000', budget_max: '1500000', skills: ['SMM', 'Design'], proposal_count: 4 },
  { id: 3, title: 'Tilida korporativ sayt yaratish', category: 'development', description: 'Kompaniya uchun tezkor, ikki tilli korporativ web-sayt.', budget_min: '3000000', budget_max: '5000000', skills: ['React', 'Django'], proposal_count: 9 },
];

export default function DashboardPage() {
  const { language, setLanguage, session, clearSession } = useApp(); const t = labels[language];
  const [view, setView] = useState('home'); const [projects, setProjects] = useState(fallbackProjects); const [query, setQuery] = useState(''); const [mobile, setMobile] = useState(false); const [notice, setNotice] = useState('');
  useEffect(() => { const controller = new AbortController(); fetchProjects({ signal: controller.signal }).then((items) => { if (items.length) setProjects(items); }).catch(() => {}); return () => controller.abort(); }, []);
  const shownProjects = useMemo(() => projects.filter((p) => `${p.title} ${p.description}`.toLowerCase().includes(query.toLowerCase())), [projects, query]);
  const fullName = session?.user?.full_name || 'Azizbek Karimov';
  async function signOut() { try { if (session?.token) await logout(session.token); } finally { clearSession(); window.location.href = '/'; } }
  function notify(message) { setNotice(message); window.setTimeout(() => setNotice(''), 2200); }
  const nav = [[Home, 'home', t.home], [UserRound, 'profile', t.profile], [BriefcaseBusiness, 'orders', t.orders], [Mail, 'messages', t.messages], [Wallet, 'wallet', t.wallet], [Settings, 'settings', t.settings]];
  return <div className="taskora-dashboard">
    <aside className={mobile ? 'open' : ''}><div className="dash-logo"><LogoMark/>Taskora<button onClick={() => setMobile(false)}><X/></button></div><nav>{nav.map(([Icon, id, name]) => <button key={id} className={view === id ? 'active' : ''} onClick={() => { setView(id); setMobile(false); }}><Icon/><span>{name}</span>{id === 'messages' && <i>3</i>}</button>)}</nav><div className="dash-user"><Avatar/><div><b>{fullName}</b><span>FREELANCER</span></div></div><button className="dash-logout" onClick={signOut}><LogOut/>{t.logout}</button></aside>
    <div className="dash-main"><header><button className="dash-menu" onClick={() => setMobile(true)}><Menu/></button><div className="dash-search"><Search/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder={language === 'uz' ? 'Buyurtmalarni qidiring' : 'Поиск заказов'}/></div><button className="dash-lang" onClick={() => setLanguage(language === 'uz' ? 'ru' : 'uz')}>{language.toUpperCase()}</button><button className="dash-bell"><Bell/><i/></button><Avatar/></header>
      <main>{view === 'home' ? <HomeView t={t} language={language} fullName={fullName} projects={shownProjects} setView={setView}/> : view === 'profile' ? <ProfileView t={t} fullName={fullName} notify={notify}/> : <SimpleView id={view} t={t} language={language} projects={shownProjects} notify={notify}/>}</main>
    </div>{notice && <div className="dash-toast"><CheckCircle2/>{notice}</div>}
  </div>;
}

function HomeView({ t, language, fullName, projects, setView }) { return <><div className="dash-welcome"><div><h1>{t.welcome}, {fullName.split(' ')[0]} 👋</h1><p>{t.subtitle}</p></div><div><button onClick={() => setView('orders')}>{t.find}</button><Link href="/register">{t.create}</Link></div></div><div className="dash-stat-grid"><Stat icon={BriefcaseBusiness} value="4" label={t.active}/><Stat icon={CheckCircle2} value="2" label={t.completed}/><Stat icon={Mail} value="18" label={t.proposals}/><Stat icon={Wallet} value="2 450 000 so‘m" label={t.earned}/></div><section className="dash-projects"><div className="dash-section-title"><div><span>{language === 'uz' ? 'YANGI BUYURTMALAR' : 'НОВЫЕ ЗАКАЗЫ'}</span><h2>{t.recommended}</h2></div><button onClick={() => setView('orders')}>{t.all}<ChevronRight/></button></div><div className="dash-project-grid">{projects.slice(0, 3).map((project) => <ProjectCard key={project.id} project={project} t={t}/>)}</div></section><section className="dash-progress"><div><span>{language === 'uz' ? 'Faol buyurtmalar' : 'Активные заказы'}</span><b>Brending — Navruz Foods</b></div><div className="progress-track"><i/></div><strong>75%</strong></section></>; }
function ProfileView({ t, fullName, notify }) { const portfolio = ['SavdoFlow — E-commerce dizayni', 'MedCare — Tibbiyot ilovasi', 'EcoHush — Ta’lim platformasi', 'Finance AI Dashboard', 'Travel mobile app', 'SaaS landing page']; return <><section className="profile-hero"><Avatar large/><div><h1>{fullName}<ShieldCheck/></h1><p>@azizbekdesign · Toshkent, O‘zbekiston</p><b>UI/UX Designer & Tilda Developer</b><span>Zamonaviy va foydalanuvchilarga qulay dizayn yaratish — mening asosiy maqsadim. 2 yildan ortiq tajriba.</span></div><div><button onClick={() => notify('Xabar oynasi ochildi')}><MessageSquare/>{t.write}</button><button onClick={() => notify('Buyurtma formasi tayyor')}><BriefcaseBusiness/>{t.order}</button></div></section><div className="profile-stats"><Stat icon={Star} value="4.9" label={t.rating}/><Stat icon={BriefcaseBusiness} value="27 loyiha" label={t.projects}/><Stat icon={Clock3} value="98%" label={t.deadline}/><Stat icon={ShieldCheck} value="2 yil Taskorada" label={t.activity}/></div><section className="profile-skills"><h2>{t.skills}</h2><div>{['UI/UX Design','Figma','Tilda','Web Design','Graphic Design'].map((skill) => <span key={skill}>{skill}</span>)}</div></section><section><div className="dash-section-title"><h2>{t.portfolio}</h2></div><div className="portfolio-grid">{portfolio.map((name, i) => <button key={name} onClick={() => notify(name)}><div className={`portfolio-art art-${i % 3}`}><span/><span/><span/></div><b>{name}</b><small>Ko‘rish →</small></button>)}</div></section></>; }
function SimpleView({ id, t, language, projects, notify }) { const title = { orders:t.orders, messages:t.messages, wallet:t.wallet, settings:t.settings }[id]; return <section className="simple-view"><span>TASKORA</span><h1>{title}</h1>{id === 'orders' ? <div className="dash-project-grid">{projects.map((project) => <ProjectCard key={project.id} project={project} t={t}/>)}</div> : <div className="simple-panel"><div className="simple-icon">{id === 'messages' ? <Mail/> : id === 'wallet' ? <Wallet/> : <Settings/>}</div><h2>{language === 'uz' ? `${title} bo‘limi` : `Раздел «${title}»`}</h2><p>{language === 'uz' ? 'Barcha kerakli funksiyalar shu yerda mavjud.' : 'Все необходимые функции доступны здесь.'}</p><button onClick={() => notify(language === 'uz' ? 'Amal bajarildi' : 'Действие выполнено')}>{language === 'uz' ? 'Davom etish' : 'Продолжить'}</button></div>}</section>; }
function Stat({ icon:Icon, value, label }) { return <article className="dash-stat"><div><span>{label}</span><b>{value}</b></div><Icon/></article>; }
function ProjectCard({ project, t }) { return <article className="dash-project-card"><div><span>{project.category || 'Design'}</span><small><Clock3/>3 kun</small></div><h3>{project.title}</h3><p>{project.description}</p><div className="project-skills">{(project.skills || []).slice(0, 3).map((skill) => <span key={skill}>{skill}</span>)}</div><footer><b>{Number(project.budget_min || 0).toLocaleString()} — {Number(project.budget_max || 0).toLocaleString()} so‘m</b><button onClick={() => window.location.href='/login'}>{t.details}</button></footer></article>; }
function Avatar({ large = false }) { return <span className={`dash-avatar ${large ? 'large' : ''}`}>AK</span>; }
function LogoMark() { return <span className="dash-logo-mark">✣</span>; }
